server:
  port: 8092
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shanzs?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 724318787
  # #redis 配置
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: redis724318787
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
# #mybatis配置
mybatis:
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath:mybatis/mapper/*.xml
  # Mybatis开启驼峰映射

  # 静态目录配置
  mvc:
    static-path-pattern: /**
  web:
    resources:
      # 静态目录地址
      static-locations: classpath:/static







